# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/facet_ui.ui'
#
# Created: Fri Jul  3 20:46:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_facetWidget(object):
    def setupUi(self, facetWidget):
        facetWidget.setObjectName("facetWidget")
        facetWidget.resize(370, 414)
        self.verticalLayout_8 = QtGui.QVBoxLayout(facetWidget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtGui.QTabWidget(facetWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.newClassTab = QtGui.QWidget()
        self.newClassTab.setObjectName("newClassTab")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.newClassTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.newClassTab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.new_nameLineEdit = QtGui.QLineEdit(self.newClassTab)
        self.new_nameLineEdit.setObjectName("new_nameLineEdit")
        self.gridLayout_2.addWidget(self.new_nameLineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.newClassTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.new_sizeLineEdit = QtGui.QLineEdit(self.newClassTab)
        self.new_sizeLineEdit.setObjectName("new_sizeLineEdit")
        self.gridLayout_2.addWidget(self.new_sizeLineEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.newClassTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.new_parentComboBox = QtGui.QComboBox(self.newClassTab)
        self.new_parentComboBox.setObjectName("new_parentComboBox")
        self.gridLayout_2.addWidget(self.new_parentComboBox, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.newClassTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.new_pointerComboBox = QtGui.QComboBox(self.newClassTab)
        self.new_pointerComboBox.setObjectName("new_pointerComboBox")
        self.gridLayout_2.addWidget(self.new_pointerComboBox, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.newClassTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.new_pointerDeltaLineEdit = QtGui.QLineEdit(self.newClassTab)
        self.new_pointerDeltaLineEdit.setObjectName("new_pointerDeltaLineEdit")
        self.gridLayout_2.addWidget(self.new_pointerDeltaLineEdit, 4, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.groupBox = QtGui.QGroupBox(self.newClassTab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.new_funcStartRButton = QtGui.QRadioButton(self.groupBox)
        self.new_funcStartRButton.setChecked(True)
        self.new_funcStartRButton.setObjectName("new_funcStartRButton")
        self.new_startAnlysisButtonGroup = QtGui.QButtonGroup(facetWidget)
        self.new_startAnlysisButtonGroup.setObjectName("new_startAnlysisButtonGroup")
        self.new_startAnlysisButtonGroup.addButton(self.new_funcStartRButton)
        self.gridLayout.addWidget(self.new_funcStartRButton, 0, 0, 1, 1)
        self.new_funcStartLineEdit = QtGui.QLineEdit(self.groupBox)
        self.new_funcStartLineEdit.setReadOnly(True)
        self.new_funcStartLineEdit.setObjectName("new_funcStartLineEdit")
        self.gridLayout.addWidget(self.new_funcStartLineEdit, 0, 1, 1, 1)
        self.new_locationRButton = QtGui.QRadioButton(self.groupBox)
        self.new_locationRButton.setObjectName("new_locationRButton")
        self.new_startAnlysisButtonGroup.addButton(self.new_locationRButton)
        self.gridLayout.addWidget(self.new_locationRButton, 1, 0, 1, 1)
        self.new_locationLineEdit = QtGui.QLineEdit(self.groupBox)
        self.new_locationLineEdit.setReadOnly(False)
        self.new_locationLineEdit.setObjectName("new_locationLineEdit")
        self.gridLayout.addWidget(self.new_locationLineEdit, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.newClassTab, "")
        self.existingClassTab = QtGui.QWidget()
        self.existingClassTab.setObjectName("existingClassTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.existingClassTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.existingClassTab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.existingClassTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.existing_sizeLineEdit = QtGui.QLineEdit(self.existingClassTab)
        self.existing_sizeLineEdit.setReadOnly(True)
        self.existing_sizeLineEdit.setObjectName("existing_sizeLineEdit")
        self.gridLayout_3.addWidget(self.existing_sizeLineEdit, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.existingClassTab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.existingClassTab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.existing_pointerComboBox = QtGui.QComboBox(self.existingClassTab)
        self.existing_pointerComboBox.setObjectName("existing_pointerComboBox")
        self.gridLayout_3.addWidget(self.existing_pointerComboBox, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.existingClassTab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 4, 0, 1, 1)
        self.existing_pointerDeltaLineEdit = QtGui.QLineEdit(self.existingClassTab)
        self.existing_pointerDeltaLineEdit.setObjectName("existing_pointerDeltaLineEdit")
        self.gridLayout_3.addWidget(self.existing_pointerDeltaLineEdit, 4, 1, 1, 1)
        self.existing_nameComboBox = QtGui.QComboBox(self.existingClassTab)
        self.existing_nameComboBox.setObjectName("existing_nameComboBox")
        self.gridLayout_3.addWidget(self.existing_nameComboBox, 0, 1, 1, 1)
        self.existing_parentLineEdit = QtGui.QLineEdit(self.existingClassTab)
        self.existing_parentLineEdit.setReadOnly(True)
        self.existing_parentLineEdit.setObjectName("existing_parentLineEdit")
        self.gridLayout_3.addWidget(self.existing_parentLineEdit, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.groupBox_2 = QtGui.QGroupBox(self.existingClassTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.existing_funcStartRButton = QtGui.QRadioButton(self.groupBox_2)
        self.existing_funcStartRButton.setChecked(True)
        self.existing_funcStartRButton.setObjectName("existing_funcStartRButton")
        self.existing_startAnlysisButtonGroup = QtGui.QButtonGroup(facetWidget)
        self.existing_startAnlysisButtonGroup.setObjectName("existing_startAnlysisButtonGroup")
        self.existing_startAnlysisButtonGroup.addButton(self.existing_funcStartRButton)
        self.gridLayout_4.addWidget(self.existing_funcStartRButton, 0, 0, 1, 1)
        self.existing_funcStartLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.existing_funcStartLineEdit.setReadOnly(True)
        self.existing_funcStartLineEdit.setObjectName("existing_funcStartLineEdit")
        self.gridLayout_4.addWidget(self.existing_funcStartLineEdit, 0, 1, 1, 1)
        self.existing_locationRButton = QtGui.QRadioButton(self.groupBox_2)
        self.existing_locationRButton.setObjectName("existing_locationRButton")
        self.existing_startAnlysisButtonGroup.addButton(self.existing_locationRButton)
        self.gridLayout_4.addWidget(self.existing_locationRButton, 1, 0, 1, 1)
        self.existing_locationLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.existing_locationLineEdit.setObjectName("existing_locationLineEdit")
        self.gridLayout_4.addWidget(self.existing_locationLineEdit, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(self.existingClassTab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.existing_cbModifyExisting = QtGui.QCheckBox(self.groupBox_6)
        self.existing_cbModifyExisting.setObjectName("existing_cbModifyExisting")
        self.verticalLayout.addWidget(self.existing_cbModifyExisting)
        self.existing_cbAssociateFunction = QtGui.QCheckBox(self.groupBox_6)
        self.existing_cbAssociateFunction.setChecked(True)
        self.existing_cbAssociateFunction.setObjectName("existing_cbAssociateFunction")
        self.verticalLayout.addWidget(self.existing_cbAssociateFunction)
        self.existing_cbFilterFacetClasses = QtGui.QCheckBox(self.groupBox_6)
        self.existing_cbFilterFacetClasses.setChecked(True)
        self.existing_cbFilterFacetClasses.setTristate(False)
        self.existing_cbFilterFacetClasses.setObjectName("existing_cbFilterFacetClasses")
        self.verticalLayout.addWidget(self.existing_cbFilterFacetClasses)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        spacerItem1 = QtGui.QSpacerItem(20, 61, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.existingClassTab, "")
        self.vfuncMarkupTab = QtGui.QWidget()
        self.vfuncMarkupTab.setObjectName("vfuncMarkupTab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.vfuncMarkupTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.vfuncTreeWidget = QtGui.QTreeWidget(self.vfuncMarkupTab)
        self.vfuncTreeWidget.setColumnCount(4)
        self.vfuncTreeWidget.setObjectName("vfuncTreeWidget")
        self.vfuncTreeWidget.headerItem().setText(0, "1")
        self.vfuncTreeWidget.headerItem().setText(1, "2")
        self.vfuncTreeWidget.headerItem().setText(2, "3")
        self.vfuncTreeWidget.headerItem().setText(3, "4")
        self.verticalLayout_7.addWidget(self.vfuncTreeWidget)
        self.vfuncSelectChildrenCheckBox = QtGui.QCheckBox(self.vfuncMarkupTab)
        self.vfuncSelectChildrenCheckBox.setChecked(True)
        self.vfuncSelectChildrenCheckBox.setObjectName("vfuncSelectChildrenCheckBox")
        self.verticalLayout_7.addWidget(self.vfuncSelectChildrenCheckBox)
        self.tabWidget.addTab(self.vfuncMarkupTab, "")
        self.relationshipsTab = QtGui.QWidget()
        self.relationshipsTab.setObjectName("relationshipsTab")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.relationshipsTab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_5 = QtGui.QGroupBox(self.relationshipsTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.relations_nameComboBox = QtGui.QComboBox(self.groupBox_5)
        self.relations_nameComboBox.setObjectName("relations_nameComboBox")
        self.gridLayout_7.addWidget(self.relations_nameComboBox, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 1, 0, 1, 1)
        self.relations_parentComboBox = QtGui.QComboBox(self.groupBox_5)
        self.relations_parentComboBox.setObjectName("relations_parentComboBox")
        self.gridLayout_7.addWidget(self.relations_parentComboBox, 1, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_7)
        spacerItem2 = QtGui.QSpacerItem(109, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.relations_saveUpdatePushButton = QtGui.QPushButton(self.groupBox_5)
        self.relations_saveUpdatePushButton.setObjectName("relations_saveUpdatePushButton")
        self.horizontalLayout_5.addWidget(self.relations_saveUpdatePushButton)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.splitter = QtGui.QSplitter(self.relationshipsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox_4 = QtGui.QGroupBox(self.splitter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.relations_containsTableWidget = QtGui.QTableWidget(self.groupBox_4)
        self.relations_containsTableWidget.setColumnCount(4)
        self.relations_containsTableWidget.setObjectName("relations_containsTableWidget")
        self.relations_containsTableWidget.setColumnCount(4)
        self.relations_containsTableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.relations_containsTableWidget)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.relations_childClassesTreeWidget = QtGui.QTreeWidget(self.groupBox_3)
        self.relations_childClassesTreeWidget.setObjectName("relations_childClassesTreeWidget")
        self.relations_childClassesTreeWidget.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.relations_childClassesTreeWidget)
        self.verticalLayout_6.addWidget(self.splitter)
        self.tabWidget.addTab(self.relationshipsTab, "")
        self.helpTab = QtGui.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.helpTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.help_textBrowser = QtGui.QTextBrowser(self.helpTab)
        self.help_textBrowser.setObjectName("help_textBrowser")
        self.verticalLayout_2.addWidget(self.help_textBrowser)
        self.tabWidget.addTab(self.helpTab, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(facetWidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_8.addWidget(self.buttonBox)

        self.retranslateUi(facetWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(facetWidget)

    def retranslateUi(self, facetWidget):
        facetWidget.setWindowTitle(QtGui.QApplication.translate("facetWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("facetWidget", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("facetWidget", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("facetWidget", "Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("facetWidget", "Pointer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("facetWidget", "Pointer Delta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("facetWidget", "Start Analysis At:", None, QtGui.QApplication.UnicodeUTF8))
        self.new_funcStartRButton.setText(QtGui.QApplication.translate("facetWidget", "Function Start", None, QtGui.QApplication.UnicodeUTF8))
        self.new_locationRButton.setText(QtGui.QApplication.translate("facetWidget", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.newClassTab), QtGui.QApplication.translate("facetWidget", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("facetWidget", "Class/Struct", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("facetWidget", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("facetWidget", "Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("facetWidget", "Pointer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("facetWidget", "Pointer Delta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("facetWidget", "Start Analysis At:", None, QtGui.QApplication.UnicodeUTF8))
        self.existing_funcStartRButton.setText(QtGui.QApplication.translate("facetWidget", "Function Start", None, QtGui.QApplication.UnicodeUTF8))
        self.existing_locationRButton.setText(QtGui.QApplication.translate("facetWidget", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("facetWidget", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.existing_cbModifyExisting.setText(QtGui.QApplication.translate("facetWidget", "Modify Existing", None, QtGui.QApplication.UnicodeUTF8))
        self.existing_cbAssociateFunction.setText(QtGui.QApplication.translate("facetWidget", "Associate function with class", None, QtGui.QApplication.UnicodeUTF8))
        self.existing_cbFilterFacetClasses.setText(QtGui.QApplication.translate("facetWidget", "Hide non-FACET structs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.existingClassTab), QtGui.QApplication.translate("facetWidget", "Existing", None, QtGui.QApplication.UnicodeUTF8))
        self.vfuncSelectChildrenCheckBox.setText(QtGui.QApplication.translate("facetWidget", "Select child classes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vfuncMarkupTab), QtGui.QApplication.translate("facetWidget", "VFunc", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("facetWidget", "Parent-Child Relationship", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("facetWidget", "Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("facetWidget", "Class", None, QtGui.QApplication.UnicodeUTF8))
        self.relations_saveUpdatePushButton.setText(QtGui.QApplication.translate("facetWidget", "Change Parent", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("facetWidget", "Contains", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("facetWidget", "Child Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.relationshipsTab), QtGui.QApplication.translate("facetWidget", "Relations", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), QtGui.QApplication.translate("facetWidget", "Help", None, QtGui.QApplication.UnicodeUTF8))

