# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/facet.ui'
#
# Created: Wed Jul  1 16:08:05 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_facetui(object):
    def setupUi(self, facetui):
        facetui.setObjectName("facetui")
        facetui.resize(327, 309)
        self.verticalLayout_2 = QtGui.QVBoxLayout(facetui)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.rb_newClass = QtGui.QRadioButton(facetui)
        self.rb_newClass.setChecked(True)
        self.rb_newClass.setObjectName("rb_newClass")
        self.gridLayout.addWidget(self.rb_newClass, 0, 0, 1, 2)
        self.line_className = QtGui.QLineEdit(facetui)
        self.line_className.setObjectName("line_className")
        self.gridLayout.addWidget(self.line_className, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(5, 10, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(facetui)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.line_objectSize = QtGui.QLineEdit(facetui)
        self.line_objectSize.setObjectName("line_objectSize")
        self.gridLayout.addWidget(self.line_objectSize, 1, 2, 1, 1)
        self.rb_existingClass = QtGui.QRadioButton(facetui)
        self.rb_existingClass.setObjectName("rb_existingClass")
        self.gridLayout.addWidget(self.rb_existingClass, 2, 0, 1, 2)
        self.combo_existingClasses = QtGui.QComboBox(facetui)
        self.combo_existingClasses.setObjectName("combo_existingClasses")
        self.gridLayout.addWidget(self.combo_existingClasses, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(facetui)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.combo_objPtrReg = QtGui.QComboBox(facetui)
        self.combo_objPtrReg.setObjectName("combo_objPtrReg")
        self.horizontalLayout_6.addWidget(self.combo_objPtrReg)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_filterUserClass = QtGui.QCheckBox(facetui)
        self.cb_filterUserClass.setChecked(True)
        self.cb_filterUserClass.setObjectName("cb_filterUserClass")
        self.gridLayout_2.addWidget(self.cb_filterUserClass, 0, 0, 1, 1)
        self.cb_modifyExisting = QtGui.QCheckBox(facetui)
        self.cb_modifyExisting.setObjectName("cb_modifyExisting")
        self.gridLayout_2.addWidget(self.cb_modifyExisting, 1, 1, 1, 1)
        self.cb_createVtable = QtGui.QCheckBox(facetui)
        self.cb_createVtable.setChecked(True)
        self.cb_createVtable.setObjectName("cb_createVtable")
        self.gridLayout_2.addWidget(self.cb_createVtable, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(facetui)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.line_delta = QtGui.QLineEdit(facetui)
        self.line_delta.setObjectName("line_delta")
        self.horizontalLayout_3.addWidget(self.line_delta)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.groupBox = QtGui.QGroupBox(facetui)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layout_startAnalysis = QtGui.QGridLayout()
        self.layout_startAnalysis.setSpacing(2)
        self.layout_startAnalysis.setObjectName("layout_startAnalysis")
        self.rb_funcStart = QtGui.QRadioButton(self.groupBox)
        self.rb_funcStart.setChecked(True)
        self.rb_funcStart.setObjectName("rb_funcStart")
        self.buttonGroup_2 = QtGui.QButtonGroup(facetui)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rb_funcStart)
        self.layout_startAnalysis.addWidget(self.rb_funcStart, 0, 0, 1, 1)
        self.line_funcStart = QtGui.QLineEdit(self.groupBox)
        self.line_funcStart.setReadOnly(True)
        self.line_funcStart.setObjectName("line_funcStart")
        self.layout_startAnalysis.addWidget(self.line_funcStart, 0, 1, 1, 1)
        self.rb_startLocation = QtGui.QRadioButton(self.groupBox)
        self.rb_startLocation.setObjectName("rb_startLocation")
        self.buttonGroup_2.addButton(self.rb_startLocation)
        self.layout_startAnalysis.addWidget(self.rb_startLocation, 1, 0, 1, 1)
        self.line_startLocation = QtGui.QLineEdit(self.groupBox)
        self.line_startLocation.setObjectName("line_startLocation")
        self.layout_startAnalysis.addWidget(self.line_startLocation, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.layout_startAnalysis)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(272, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pb_cancel = QtGui.QPushButton(facetui)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout_4.addWidget(self.pb_cancel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pb_run = QtGui.QPushButton(facetui)
        self.pb_run.setObjectName("pb_run")
        self.horizontalLayout_4.addWidget(self.pb_run)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(facetui)
        QtCore.QMetaObject.connectSlotsByName(facetui)

    def retranslateUi(self, facetui):
        facetui.setWindowTitle(QtGui.QApplication.translate("facetui", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_newClass.setText(QtGui.QApplication.translate("facetui", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("facetui", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_existingClass.setText(QtGui.QApplication.translate("facetui", "Existing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("facetui", "Object Pointer", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_filterUserClass.setText(QtGui.QApplication.translate("facetui", "Filter\n"
"User Structs", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_modifyExisting.setText(QtGui.QApplication.translate("facetui", "Modify Existing", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_createVtable.setText(QtGui.QApplication.translate("facetui", "Create Vtable", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("facetui", "Pointer\n"
"Delta", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("facetui", "Start Analysis At", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_funcStart.setText(QtGui.QApplication.translate("facetui", "Function Start", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_startLocation.setText(QtGui.QApplication.translate("facetui", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel.setText(QtGui.QApplication.translate("facetui", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_run.setText(QtGui.QApplication.translate("facetui", "Run", None, QtGui.QApplication.UnicodeUTF8))

